### ISSUE TITLE
Reference ticker is always undefined

### ISSUE THREAD

**Issue by alanshaw** [tes/big-red#4]
No way to clear the polling interval

I think `ticker()` may have once returned a intervalObject which could be used to clear the ticker but since entropy was added to the function with `setTimeout` this is no longer the case.

https://github.com/tes/big-red/blob/beb00306a25c817c30786b27939438f04a52cdf1/lib/big-red.js#L35-L41

**Comment by cliftonc** [comment]
This is fixed in the same commit that closed #5 - the entropy isn't really required.
