### ISSUE TITLE
Potential memory leak when calling load multiple times

### ISSUE THREAD

**Issue by alanshaw** [tes/big-red#5]
Multiple calls to `load(['foo'])` will create multiple [interval pollers](https://github.com/tes/big-red/blob/beb00306a25c817c30786b27939438f04a52cdf1/lib/big-red.js#L135) for the same dataset as there is no check to see if the reference has already been loaded.

If a `poller` function blindly returns true then every poll is going to hit the database (or whatever backend store the `retriever` function is using).

I'd originally put my `load` call in a request handler, so you can see how this might have got out of hand quickly!

**Comment by cliftonc** [comment]
Well spotted, I had definitely not considered anyone calling ``load()``` more than once, but it should deal with this situation properly and not re-load with new pollers.

The idiomatic usage is to load it once on start up and then pass the reference through into your controllers.

I'll fix it up.
